sudo: false
language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

install:
  - cat composer.json
  - composer self-update
  - rm composer.lock
  - composer install -o --profile

script: vendor/bin/phpunit
